/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2026-01-06T23:07:41.590Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "7e1e01c3-1f9d-45c8-b8dc-1c7d281e99fb",
    name: "Local News",
    slug: "local-news",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "ff58da11-91a4-4a40-b646-dfb53111d09a",
        name: "Community Events",
        slug: "community-events",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "ee2ed587-4050-48f7-b5ec-bffef9a0bf44",
        name: "Crime & Safety",
        slug: "crime--safety",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "dda0c2ac-27b0-4210-8a7d-e80276609b23",
        name: "Local Government",
        slug: "local-government",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "c95fff8d-ca01-4072-b2b6-30bb599234c1",
    name: "State Politics",
    slug: "state-politics",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "3583c2c2-bc72-456a-9670-39e5936b0b11",
        name: "Legislation",
        slug: "legislation",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "9e55f115-d6ab-4e50-98f7-1677e2bb94c0",
        name: "Elections",
        slug: "elections",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "871e9afb-93e0-48af-babb-49a38ab1aa42",
        name: "Political Commentary",
        slug: "political-commentary",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "24cf8ad4-821e-4e0a-b9bc-9a726b257fe8",
    name: "Business & Economy",
    slug: "business--economy",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "38ca1ba9-c5e9-424a-a726-87685eba57e0",
        name: "Local Business",
        slug: "local-business",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "4ea473ae-83f8-4e7e-bb7d-a9565cdaee4b",
        name: "Economic Development",
        slug: "economic-development",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "4529cc9c-9582-4d08-940e-c6101233c5be",
        name: "Trade & Tariffs",
        slug: "trade--tariffs",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "f2fa0b97-6c14-4303-9590-c25e1e089225",
    name: "Sports",
    slug: "sports",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "06e7193a-bdbc-411e-8dbc-53fab33a6ac8",
        name: "High School Sports",
        slug: "high-school-sports",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "b1fb9005-af0a-411c-a6fe-c50c63a4e5f7",
        name: "Local Teams",
        slug: "local-teams",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "1f0ead04-a577-4b6c-a14f-1eade9f4a90d",
        name: "Athlete Features",
        slug: "athlete-features",
        showInHeader: true,
        showInFooter: true
      }
    ]
  }
]
