/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: Oregon Pulse
 * Generated: 2026-01-06T23:07:41.590Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "1ccb2791-fc48-4530-8012-0f7c1c6f8140",
    name: "Oregon Pulse",
    description: "Oregon Pulse delivers dynamic, real-time coverage of local news, community stories, and regional developments, keeping the heart of Oregon informed and engaged.",
    url: "https://oregon-pulse-blog.vercel.app",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Bringing Oregon's stories to your doorstep, one pulse at a time"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to Oregon Pulse",
    subtitle: "Bringing Oregon's stories to your doorstep, one pulse at a time"
  },

  // Default author information
  author: {
    name: "Oregon Pulse Team",
    bio: "Oregon Pulse delivers dynamic, real-time coverage of local news, community stories, and regional developments, keeping the heart of Oregon informed...",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Local News and Media Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from Oregon Pulse delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Local Business",
      icon: "FileText",
      slug: "local-business"
    },
    { 
      name: "Local News",
      icon: "Newspaper",
      slug: "local-news"
    },
    { 
      name: "High School Sports",
      icon: "FileText",
      slug: "high-school-sports"
    },
    { 
      name: "Legislation",
      icon: "FileText",
      slug: "legislation"
    },
    { 
      name: "Community Events",
      icon: "FileText",
      slug: "community-events"
    },
    { 
      name: "Economic Development",
      icon: "FileText",
      slug: "economic-development"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "c1a4a74e-aed2-49b1-b2f6-0665e2b83708",
      name: "Emily Carter",
      bio: "Emily is a passionate storyteller with a knack for uncovering the human side of local news. Her writing style is engaging and accessible, making complex stories relatable to everyday readers. With a background in investigative journalism, she excels at digging deep into community issues and bringing them to light with clarity and compassion.",
      image: "/authors/c1a4a74e-aed2-49b1-b2f6-0665e2b83708.jpg",
      role: "Senior Local News Reporter"
    },
    {
      id: "efb6ff1b-d8de-4bca-b0ad-278804acdc82",
      name: "Michael Thurston",
      bio: "Michael brings a vibrant and energetic voice to his sports and community coverage. His expertise in local sports and community events allows him to capture the pulse of Oregon's diverse athletic and cultural landscape. Known for his lively and enthusiastic writing, Michael connects with readers through stories that celebrate the spirit and resilience of the local community.",
      image: "/authors/efb6ff1b-d8de-4bca-b0ad-278804acdc82.jpg",
      role: "Sports and Community Correspondent"
    },
    {
      id: "f9a05115-8901-46be-a109-3aabd4e0f887",
      name: "Sophia Nguyen",
      bio: "Sophia is a sharp and insightful analyst with a focus on political and business developments in Oregon. Her writing is characterized by a meticulous attention to detail and a balanced perspective, offering readers well-rounded insights into the intricacies of regional politics and economic trends. Sophia's authoritative voice and analytical prowess make her a trusted source for in-depth reporting and thoughtful commentary.",
      image: "/authors/f9a05115-8901-46be-a109-3aabd4e0f887.jpg",
      role: "Political and Business Analyst"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
